---
- hosts: all
  become: yes
  tasks:
    - name: Update Cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
- hosts: localhost
  vars:
    - server_hostname: project_pms18.hua.gr
    - key_size: 4096
    - passphrase: # Set if you want passphrase
    - key_type: RSA # Others include DSA, ECC, Ed25519, Ed448, X25519, X448
    - country_name: GR
    - email_address: itp20103@hua.gr
    - organization_name: HUA
  tasks:
    - name: create ../files/certs directory
      file:
        path: ../files/certs
        state: directory
    - name: Generate an OpenSSL private key
      openssl_privatekey:
        path: "../files/certs/server.key"
        size: "{{ key_size }}"
        type: "{{ key_type }}"
        backup: yes
    - name: Generate an OpenSSL Certificate Signing Request with Subject information
      openssl_csr:
        path: "../files/certs/server.csr"
        privatekey_path: "../files/certs/server.key"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ server_hostname }}"
    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: "../files/certs/server.crt"
        privatekey_path: "../files/certs/server.key"
        csr_path: "../files/certs/server.csr"
        provider: selfsigned