---
- hosts: all
  become: yes
  tasks:
    - name: Update Cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: app02
  
  vars:
    user_dir: "/home/vagrant"
    owncloud_url: "https://download.owncloud.org/community/owncloud-complete-20210326.tar.bz2"
  
  tasks:

  - name: Add PHP Repository
    apt_repository:
      validate_certs: no
      repo: ppa:ondrej/php
      state: present
    become: yes

  - name: "APT - Install Prerequisites"
    apt:
      pkg: 
        - apache2
        - php7.3
        - libapache2-mod-php7.3
        - php7.3-pgsql
        - php7.3-intl
        - php7.3-curl
        - php7.3-json
        - php7.3-gd
        - php7.3-xml
        - php7.3-mbstring
        - php7.3-zip
        - php7.3-opcache
        - postgresql-client
      update_cache: yes
      cache_valid_time: 3600
    become: yes
    when: hostvars[inventory_hostname].ansible_distribution == 'Ubuntu'
    notify: restart apache2

  - name: Create owncloud database
    postgresql_db:
      name: "{{db.name}}"
    become: yes
    become_user: postgres
    delegate_to: "{{db.host}}"
    run_once: yes
  
  - name: Create owncloud db user
    postgresql_user:
      name: "{{db.user}}"
      password: "{{db.pass}}"
      state: present
    become: yes
    become_user: postgres
    delegate_to: "{{db.host}}"
    run_once: yes

  - name: Grant privileges on owncloud db user to owncloud db 
    postgresql_privs:
      privs: ALL
      database: "{{db.name}}"
      roles: "{{db.user}}"
      type: database
    become: yes
    become_user: postgres
    delegate_to: "{{db.host}}"
    run_once: yes  
  
  - name: Download owncloud
    get_url:
      url: "{{owncloud_url}}"
      dest: "{{user_dir}}"
      #force: yes
  
  - name: Unarchive downloaded file 
    ansible.builtin.unarchive:
      src: /home/vagrant/owncloud-complete-20210326.tar.bz2
      dest: /var/www
      remote_src: yes
    become: yes
  
  - name: Copy ownlcloud conf file
    template:
      src: ../files/owncloud.conf
      dest: "/etc/apache2/sites-available/owncloud.conf"
    become: yes

  - name: Enable owncloud site on apache
    file:
      src: "/etc/apache2/sites-available/owncloud.conf"
      dest: "/etc/apache2/sites-enabled/owncloud.conf"
      state: link
    become: yes
    notify: restart apache2

  - name: Enable apache rewrite module
    apache2_module:
      name: rewrite
      state: present
      ignore_configcheck: True
    become: yes
    notify: restart apache2
  
  - name: Change ownership of owncloud directory
    file:
      path: /var/www/owncloud
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
    become: yes
    notify: restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
      become: yes